before_script:
    - apt update
    - apt install --assume-yes cmake qtbase5-dev

stages:
    - build

job 1:
    stage: build
    script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
